version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: mysql
      working_dir: /application
      volumes:
        - ./db_data:/application
        - ./phpdocker/sql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
        - ./sql/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql:ro
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=app
        - MYSQL_USER=app
        - MYSQL_PASSWORD=app
        - MYSQL_CHARSET=cp1251
      ports:
        - "5002:3306"

    webserver:
      image: nginx:alpine
      container_name: app-webserver
      working_dir: /application
      volumes:
          - ./src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "5000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: app-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      environment:
        - DBHOST=mysql
        - DATABASE=app
        - DBUSER=app
        - DBPASSWORD=app
        
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: PhpMyAdmin
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_PORT=3306
        - MYSQL_USERNAME=app
        - MYSQL_ROOT_PASSWORD=root
      restart: always
      ports:
        - "5050:80"
      depends_on:
        - mysql
